### ISSUE TITLE
Expose claim/promise to client

### ISSUE THREAD

**Issue by galabra** [nonZero/TruePolitics#6]
We'd like to filter articles by טענת/הבטחת שווא.
In order to do that, we need to add this field to the article model that is exposed to the client

**Comment by nonZero** [comment]
@galabra 

https://cms.true.org.il/s/json/

![image](https://user-images.githubusercontent.com/66484/233482533-e74e8b13-511a-4e1f-a0b3-86c59cca67e1.png)


![image](https://user-images.githubusercontent.com/66484/233482429-23182557-87c6-4235-a66f-8aba98c256c3.png)
